name: MainWorkflow
on: [workflow_dispatch]
jobs:
  UpdateVersion:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3
      - name: update version
        working-directory: ./src
        run: python update_version.py
      - name: commit changes
        uses: EndBug/add-and-commit@v9.1.1
        with:
          default_author: github_actions
          message: 'Update version'

  TrainTree:
    runs-on: ubuntu-latest
    needs: UpdateVersion
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3
      - name: install script requirements
        run: pip install -r src/requirements.txt
      - name: train model an save result
        working-directory: ./src
        env:
          DB_USERNAME: github
          DB_PASSWORD: ${{secrets.DBPASSWORD}}
        run: python train_model.py "tree"

  TrainKNN:
    runs-on: ubuntu-latest
    needs: UpdateVersion
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3
      - name: install script requirements
        run: pip install -r src/requirements.txt
      - name: train model an save result
        working-directory: ./src
        env:
          DB_USERNAME: github
          DB_PASSWORD: ${{secrets.DBPASSWORD}}
        run: python train_model.py "knn"

  TrainNN:
    runs-on: self-hosted
    needs: UpdateVersion
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3
      - name: train model an save result
        working-directory: ./src
        env:
          DB_USERNAME: github
          DB_PASSWORD: ${{secrets.DBPASSWORD}}
        run: conda activate CV_screening; python train_model.py "nn"

  EvalTree:
    runs-on: ubuntu-latest
    needs: TrainTree
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3
      - name: install script requirements
        run: pip install -r src/requirements.txt
      - name: eval model
        working-directory: ./src
        env:
          DB_USERNAME: github
          DB_PASSWORD: ${{secrets.DBPASSWORD}}
        run: python evaluate_model.py "tree"

  EvalKNN:
    runs-on: ubuntu-latest
    needs: TrainKNN
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3
      - name: install script requirements
        run: pip install -r src/requirements.txt
      - name: eval model
        working-directory: ./src
        env:
          DB_USERNAME: github
          DB_PASSWORD: ${{secrets.DBPASSWORD}}
        run: python evaluate_model.py "knn"

  EvalNN:
    runs-on: self-hosted
    needs: TrainNN
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3
      - name: eval model
        working-directory: ./src
        env:
          DB_USERNAME: github
          DB_PASSWORD: ${{secrets.DBPASSWORD}}
        run: conda activate CV_screening; python evaluate_model.py "nn"

  SelectModel:
    runs-on: ubuntu-latest
    needs: [EvalTree, EvalKNN, EvalNN]
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3
      - name: install script requirements
        run: pip install -r src/requirements.txt
      - name: eval model
        working-directory: ./src
        env:
          DB_USERNAME: github
          DB_PASSWORD: ${{secrets.DBPASSWORD}}
        run: python model_selection.py

  DeployModel:
    runs-on: self-hosted
    needs: SelectModel
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3
      - name: deploy model
        working-directory: ./src
        env:
          DB_USERNAME: github
          DB_PASSWORD: ${{secrets.DBPASSWORD}}
        run: python update_server.py