name: Main Workflow
on: [workflow_dispatch]
jobs:
  LoadDataset:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content
      - run: pip install kaggle
      - run: mkdir ~/.kaggle
      - run: cp ./kaggle.json ~/.kaggle
      - run: kaggle datasets download leenardeshmukh/curriculum-vitae
      - run: unzip curriculum-vitae.zip
      - run: pip install -r requirements.txt
      - run: python src/data_loading/fill_database.py "Curriculum Vitae.csv"
