name: MainWorkflow
on: [workflow_dispatch]
jobs:
  UpdateVersion:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2
      - name: change workdir
        run: cd src
      - name: update version
        run: python update_version.py
      - name: commit changes
        uses: EndBug/add-and-commit@v9.1.1
        with:
          message: 'Update version'

  TrainTree:
    runs-on: ubuntu-latest
    needs: UpdateVersion
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2
      - name: change workdir
        run: cd src
      - name: install script requirements
        run: pip install -r src/requirements.txt
      - name: train model an save result
        env:
          DB_USERNAME: github
          DB_PASSWORD: ${{secrets.DBPASSWORD}}
        run: python train_model.py "tree"

  TrainKNN:
    runs-on: ubuntu-latest
    needs: UpdateVersion
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2
      - name: change workdir
        run: cd src
      - name: install script requirements
        run: pip install -r src/requirements.txt
      - name: train model an save result
        env:
          DB_USERNAME: github
          DB_PASSWORD: ${{secrets.DBPASSWORD}}
        run: python train_model.py "knn"

  TrainNN:
    runs-on: ubuntu-latest
    needs: UpdateVersion
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2
      - name: change workdir
        run: cd src
      - name: install script requirements
        run: pip install -r src/requirements.txt
      - name: install tensorflow
        run: pip install tensorflow keras
      - name: train model an save result
        env:
          DB_USERNAME: github
          DB_PASSWORD: ${{secrets.DBPASSWORD}}
        run: python train_model.py "nn"
